# Generated by Django 5.1.7 on 2025-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_master_photo_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(blank=True, default='masters/default_master.jpg', null=True, upload_to='masters/', verbose_name='Фотография'),
        ),
    ]
