# Generated by Django 5.1.7 on 2025-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_master_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-date_created'], name='core_order_status_21e56b_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_popular'], name='core_servic_is_popu_7bf01a_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['price'], name='core_servic_price_72c8b6_idx'),
        ),
    ]
