# Generated by Django 5.1.7 on 2025-06-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='master',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Сколько раз просмотрена страница мастера', verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отображать ли отзыв на сайте', verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='review',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.master', verbose_name='Мастер'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['is_active'], name='core_master_is_acti_662e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['appointment_date'], name='core_order_appoint_01d27a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_published', 'rating'], name='core_review_is_publ_4771c8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='core_review_created_25a366_idx'),
        ),
    ]
